

export const lineChart = {
    "budgetNumber": {
        "currencyCode": "USD",
        "format": "percentage",
        "number": 0.2
    },
    "context": {
        "category": {
            "health": 2,
            "id": "ALL",
            "name": "Business: All"
        },
        "endDate": "FY17",
        "geography": {
            "health": 0,
            "id": "ALL",
            "name": "World Wide"
        },
        "product": {
            "health": 0,
            "id": "ALL",
            "name": "All Products"
        },
        "startDate": "FY12"
    },
    "forecastNumber": {
        "currencyCode": "USD",
        "format": "percentage",
        "number": 0.4
    },
    "insightText": "Perfect Order Type Data",
    "chartData": {
        "lineGraphData": {
            "lines": [
                [
                    {
                        "budget": null,
                        "currencyCode": "",
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": "15 Q1",
                        "forecast": null,
                        "format": "Average/Int",
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": "NPS",
                        "maxScale": null,
                        "minScale": null,
                        "number": 23.7,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": "",
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": "15 Q2",
                        "forecast": null,
                        "format": "Average/Int",
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": "NPS",
                        "maxScale": null,
                        "minScale": null,
                        "number": 38.1,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": "",
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": "15 Q3",
                        "forecast": null,
                        "format": "Average/Int",
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": "NPS",
                        "maxScale": null,
                        "minScale": null,
                        "number": 41.3,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": "",
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": "15 Q4",
                        "forecast": null,
                        "format": "Average/Int",
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": "NPS",
                        "maxScale": null,
                        "minScale": null,
                        "number": 31.6,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": "",
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": "16 Q1",
                        "forecast": null,
                        "format": "Average/Int",
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": "NPS",
                        "maxScale": null,
                        "minScale": null,
                        "number": 41.3,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": "",
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": "16 Q2",
                        "forecast": null,
                        "format": "Average/Int",
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": "NPS",
                        "maxScale": null,
                        "minScale": null,
                        "number": 51.4,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": "",
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": "16 Q3",
                        "forecast": null,
                        "format": "Average/Int",
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": "NPS",
                        "maxScale": null,
                        "minScale": null,
                        "number": 41.5,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": "",
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": "16 Q4",
                        "forecast": null,
                        "format": "Average/Int",
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": "NPS",
                        "maxScale": null,
                        "minScale": null,
                        "number": 27.3,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": "",
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": "17 Q1",
                        "forecast": null,
                        "format": "Average/Int",
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": "NPS",
                        "maxScale": null,
                        "minScale": null,
                        "number": 40.7,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": "",
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": "17 Q2",
                        "forecast": null,
                        "format": "Average/Int",
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": "NPS",
                        "maxScale": null,
                        "minScale": null,
                        "number": 49.6,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    }
                ]
            ],
            "maxNumber": 51.4,
            "minNumber": 23.7,
            "referenceLines": [
                [
                    {
                        "budget": null,
                        "currencyCode": "",
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": "2016",
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": "Farm Value",
                        "maxScale": null,
                        "minScale": null,
                        "number": 42.12,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    }
                ]
            ],
            "supportLines": [
                [
                    {
                        "budget": null,
                        "currencyCode": "",
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": "2015",
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": "Leader in Innovation",
                        "maxScale": null,
                        "minScale": null,
                        "number": 27.81,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": "",
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": "2016",
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": "Leader in Innovation",
                        "maxScale": null,
                        "minScale": null,
                        "number": 34.7,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    }
                ],
                [
                    {
                        "budget": null,
                        "currencyCode": "",
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": "2015",
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": "Agro Support",
                        "maxScale": null,
                        "minScale": null,
                        "number": 37.63,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": "",
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": "2016",
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": "Agro Support",
                        "maxScale": null,
                        "minScale": null,
                        "number": 40.09,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    }
                ],
                [
                    {
                        "budget": null,
                        "currencyCode": "",
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": "2015",
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": "Farm Value",
                        "maxScale": null,
                        "minScale": null,
                        "number": 33.92,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": "",
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": "2016",
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": "Farm Value",
                        "maxScale": null,
                        "minScale": null,
                        "number": 42.12,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    }
                ],
                [
                    {
                        "budget": null,
                        "currencyCode": "",
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": "2015",
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": "Ease of Doing Business",
                        "maxScale": null,
                        "minScale": null,
                        "number": 35.84,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": "",
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": "2016",
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": "Ease of Doing Business",
                        "maxScale": null,
                        "minScale": null,
                        "number": 40.72,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    }
                ],
                [
                    {
                        "budget": null,
                        "currencyCode": "",
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": "2015",
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": "Product & Portfolio Offering",
                        "maxScale": null,
                        "minScale": null,
                        "number": 39,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": "",
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": "2016",
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": "Product & Portfolio Offering",
                        "maxScale": null,
                        "minScale": null,
                        "number": 42,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    },
                    {
                        "budget": null,
                        "currencyCode": null,
                        "displayNumber": null,
                        "displayNumberCurrencyCode": null,
                        "displayNumberFormat": null,
                        "for": null,
                        "forecast": null,
                        "format": null,
                        "health": null,
                        "icon": null,
                        "indicator": null,
                        "label": null,
                        "maxScale": null,
                        "minScale": null,
                        "number": null,
                        "percentOfTotal": null,
                        "target": null,
                        "trend": null,
                        "units": null
                    }
                ]
            ],
            "xaxisLabels": [
                "15 Q1",
                "15 Q2",
                "15 Q3",
                "15 Q4",
                "16 Q1",
                "16 Q2",
                "16 Q3",
                "16 Q4",
                "17 Q1",
                "17 Q2"
            ]
        }
    },
    "kpiMetadata": {
        "allowDrillDown": false,
        "category": "Details",
        "chartType": "lineGraph",
        "chartTypeDetail": "lineGraph",
        "definition": "Amount of sales generated after deduction of returns, allowances for damaged or missing goods and discounts.",
        "equation": "Gross Sales � Return and Replants � Market Funding",
        "hasBusinessesHubsDetail": true,
        "hasCategoriesDetail": true,
        "kpiId": "net-sales",
        "kpiType": "quadruple",
        "name": "Quadruple Line Graph with Support Lines",
        "pointOfContactEmail": "taggardandrews@kpmg.com",
        "pointOfContactPingId": "TANDR2",
        "shortName": "Net Sales",
        "showComments": true,
        "showNumberBar": false
    },
    "kpiOverview": {
        "actualNumber": {
            "currencyCode": "",
            "format": "",
            "number": 1066
        },
        "budgetNumber": {
            "currencyCode": "",
            "format": "",
            "units": "visits"
        },
        "context": {
            "category": {
                "compareType": "geos",
                "id": "ALL",
                "name": "Business: All"
            },
            "endDate": "01/17",
            "geography": {
                "compareType": "geos",
                "id": "ALL",
                "name": "World Wide"
            },
            "product": {
                "compareType": "products",
                "health": 0,
                "id": "ALL",
                "name": "All Categories"
            },
            "startDate": "01/10"
        },
        "forecastNumber": {
            "currencyCode": "",
            "format": "",
            "units": "visits"
        },
        "insightText": "Time with Customers Headline - January 2017",
        "chartData": {
            "segmentedDonutData": {
                "segmentNumbers": [
                    {
                        "label": "Other",
                        "numData": {
                            "format": "percentage",
                            "number": 0.43,
                            "percentOfTotal": 0.43,
                            "units": "visits"
                        }
                    },
                    {
                        "label": "Retain",
                        "numData": {
                            "format": "percentage",
                            "number": 0.03,
                            "percentOfTotal": 0.03,
                            "units": "visits"
                        }
                    },
                    {
                        "label": "Acquire",
                        "numData": {
                            "format": "percentage",
                            "number": 0.08,
                            "percentOfTotal": 0.08,
                            "units": "visits"
                        }
                    },
                    {
                        "label": "Develop",
                        "numData": {
                            "format": "percentage",
                            "number": 0.36,
                            "percentOfTotal": 0.36,
                            "units": "visits"
                        }
                    },
                    {
                        "label": "Light Touch",
                        "numData": {
                            "format": "percentage",
                            "number": 0.1,
                            "percentOfTotal": 0.1,
                            "units": "visits"
                        }
                    }
                ],
                "summaryNumber": {
                    "format": "",
                    "label": "Total",
                    "number": 1066,
                    "units": "visits"
                }
            }
        },
        "kpiMetadata": {
            "allowDrillDown": true,
            "category": "Customer",
            "chartType": "segmentedDonut",
            "chartTypeDetail": "segmentedLines",
            "definition": "Any contact with the customer recorded by sales representatives.",
            "detailMeasures": [],
            "equation": "Sum of All Touch Points",
            "hasBusinessesHubsDetail": true,
            "hasCategoriesDetail": true,
            "healthVariancePercent": 0.03,
            "kpiId": "twc",
            "kpiOwners": [
                {
                    "email": "angela.kyster@monsanto.com",
                    "geoId": "HUBEME",
                    "name": "Angela Kyster"
                },
                {
                    "email": "natalia.m.modolo@monsanto.com",
                    "geoId": "HUBSA",
                    "name": "Natalia Modolo"
                },
                {
                    "email": "luke.burbank@monsanto.com",
                    "geoId": "HUBNA",
                    "name": "Luke Burbank"
                }
            ],
            "kpiType": "single",
            "largerNumberIsHealthier": true,
            "name": "Time with Customers",
            "pointOfContactEmail": "geetanjali.tandon@monsanto.com",
            "pointOfContactName": "Geetanjali Tandon",
            "pointOfContactPingId": "",
            "replaceActualWithPriorForecast": false,
            "shortName": "Time with Customers",
            "showComments": true,
            "showNumberBar": true,
            "usePercentChangeOverTimeInKpiData": false,
            "watch": true
        },
        "lastRefreshDate": "2015-10-23T18:25:43.511Z",
        "newCommentCount": 0,
        "trending": false,
        "previousActualNumber": {
            "currencyCode": "",
            "format": "",
            "units": "visits"
        },
        "previousForecastNumber": {
            "currencyCode": "",
            "format": "",
            "units": "visits"
        },
        "priorYearActualNumber": {
            "currencyCode": "",
            "format": "",
            "units": "visits"
        },
        "priority": 21,
        "source": "SFDC",
        "totalCommentCount": 0,
        "yearToDateNumber": {
            "currencyCode": "",
            "format": "",
            "units": "visits"
        }
    },
    "lastRefreshDate": "2015-10-23T18:23:00.00Z",
    "newCommentCount": 0,
    "trending": false,
    "previousForecastNumber": {
        "currencyCode": "USD",
        "format": "currency",
        "number": 13048451120.5
    },
    "priority": 1,
    "priorYearActualNumber": {
        "currencyCode": "USD",
        "format": "currency",
        "number": 776833225.34
    },
    "source": "HFM_Mgt",
    "totalCommentCount": 1,
    "yearToDateNumber": {
        "currencyCode": "USD",
        "format": "currency",
        "number": 1705459120.5
    },
    "kpiSummary": [
        {
            "values": [
                {
                    "numberType": "forecast",
                    "numbers": [
                        {
                            "format": "currency",
                            "number": 500000000
                        }
                    ]
                },
                {
                    "numberType": "actual",
                    "numbers": [
                        {
                            "format": "currency",
                            "number": 640000000,
                            "trend": "negative",
                            "indicator": "up"
                        }
                    ]
                },
                {
                    "numberType": "budget",
                    "numbers": [
                        {
                            "format": "currency",
                            "number": 800000000,
                            "trend": "negative",
                            "indicator": "down"
                        }
                    ]
                },
                {
                    "numberType": "priorYearActual",
                    "numbers": [
                        {
                            "format": "currency",
                            "number": 880000000,
                            "trend": "positive",
                            "indicator": "down"
                        }
                    ]
                }
            ]
        }
    ]
}

export const barData = {
    "actualNumber": {
        "currencyCode": "",
        "format": "average/int",
        "number": 80.85
    },
    "budgetNumber": {
        "currencyCode": "",
        "format": "average/int",
        "number": 80.72
    },
    "forecastNumber": {
        "currencyCode": "",
        "format": "average/int"
    },
    "insightText": "NPS Headline - World Wide",
    "chartData": {
        "barChartData": {
            "maxNumber": 636224,
            "minNumber": 0,
            "numbers": [
                {
                    "budget": 0,
                    "currencyCode": null,
                    "displayNumber": null,
                    "displayNumberCurrencyCode": null,
                    "displayNumberFormat": null,
                    "for": null,
                    "forecast": null,
                    "format": "average/int",
                    "health": null,
                    "icon": null,
                    "indicator": null,
                    "label": "Baseline",
                    "maxScale": null,
                    "minScale": null,
                    "number": 257000,
                    "percentOfTotal": null,
                    "target": 0,
                    "trend": null,
                    "units": null
                },
                {
                    "budget": 257000,
                    "currencyCode": null,
                    "displayNumber": null,
                    "displayNumberCurrencyCode": null,
                    "displayNumberFormat": null,
                    "for": null,
                    "forecast": null,
                    "format": "average/int",
                    "health": null,
                    "icon": null,
                    "indicator": null,
                    "label": "2016",
                    "maxScale": null,
                    "minScale": null,
                    "number": 46088,
                    "percentOfTotal": null,
                    "target": 0,
                    "trend": null,
                    "units": null
                },
                {
                    "budget": 303088,
                    "currencyCode": null,
                    "displayNumber": null,
                    "displayNumberCurrencyCode": null,
                    "displayNumberFormat": null,
                    "for": null,
                    "forecast": null,
                    "format": "average/int",
                    "health": null,
                    "icon": null,
                    "indicator": null,
                    "label": "2017",
                    "maxScale": null,
                    "minScale": null,
                    "number": 273854,
                    "percentOfTotal": null,
                    "target": 473792,
                    "trend": null,
                    "units": null
                },
                {
                    "budget": 576942,
                    "currencyCode": null,
                    "displayNumber": null,
                    "displayNumberCurrencyCode": null,
                    "displayNumberFormat": null,
                    "for": null,
                    "forecast": null,
                    "format": "average/int",
                    "health": null,
                    "icon": null,
                    "indicator": null,
                    "label": "2018",
                    "maxScale": null,
                    "minScale": null,
                    "number": 59282,
                    "percentOfTotal": null,
                    "target": 776424,
                    "trend": null,
                    "units": null
                },
                {
                    "budget": 636224,
                    "currencyCode": null,
                    "displayNumber": null,
                    "displayNumberCurrencyCode": null,
                    "displayNumberFormat": null,
                    "for": null,
                    "forecast": null,
                    "format": "average/int",
                    "health": null,
                    "icon": null,
                    "indicator": null,
                    "label": "2019",
                    "maxScale": null,
                    "minScale": null,
                    "number": 0,
                    "percentOfTotal": null,
                    "target": 766038,
                    "trend": null,
                    "units": null
                },
                {
                    "budget": 0,
                    "currencyCode": null,
                    "displayNumber": null,
                    "displayNumberCurrencyCode": null,
                    "displayNumberFormat": null,
                    "for": null,
                    "forecast": null,
                    "format": "average/int",
                    "health": null,
                    "icon": null,
                    "indicator": null,
                    "label": "Strive for Five Cumulative",
                    "maxScale": null,
                    "minScale": null,
                    "number": 636224,
                    "percentOfTotal": null,
                    "target": 757000,
                    "trend": null,
                    "units": null
                }
            ]
        }
    },
    "kpiMetadata": {
        "allowDrillDown": true,
        "category": "customer",
        "chartType": "waterfallChart",
        "definition": "Actual - Expected",
        "detailMeasures": [],
        "equation": "Adjustment against expected value",
        "hasBusinessesHubsDetail": true,
        "hasCategoriesDetail": true,
        "healthVariancePercent": 0.03,
        "kpiId": "net-sales-budget",
        "kpiOwners": [],
        "kpiType": "quadruple",
        "largerNumberIsHealthier": true,
        "name": "Water Fall Bar Chart",
        "pointOfContactEmail": "dennis.j.steiner@monsanto.com",
        "pointOfContactPingId": "",
        "replaceActualWithPriorForecast": true,
        "shortName": "Net Sales Budget",
        "showComments": false,
        "showNumberBar": false
    },
    "lastRefreshDate": "2016-11-19T19:34:57.901Z",
    "newCommentCount": 0,
    "trending": false,
    "previousForecastNumber": {
        "currencyCode": "",
        "format": "average/int",
        "number": 34.59
    },
    "priority": 21,
    "source": "SFDC",
    "totalCommentCount": 3
}